// @vitest-environment jsdom

import { act } from "react";
import { createRoot } from "react-dom/client";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { MemoryRouter, Route, Routes } from "react-router-dom";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { DeliverableDetail } from "./DeliverableDetail";

const getMock = vi.hoisted(() => vi.fn());
const setBreadcrumbsMock = vi.hoisted(() => vi.fn());

vi.mock("@/api/deliverables", () => ({
  deliverablesApi: {
    get: (id: string) => getMock(id),
  },
}));

vi.mock("@/context/CompanyContext", () => ({
  useCompany: () => ({
    selectedCompanyId: "company-1",
    selectedCompany: { id: "company-1", name: "Bizbox", issuePrefix: "PAP" },
  }),
}));

vi.mock("@/context/BreadcrumbContext", () => ({
  useBreadcrumbs: () => ({ setBreadcrumbs: setBreadcrumbsMock }),
}));

vi.mock("../components/MarkdownBody", () => ({
  MarkdownBody: ({ children, className }: { children: string; className?: string }) => (
    <div className={className}>{children}</div>
  ),
}));

// eslint-disable-next-line @typescript-eslint/no-explicit-any
(globalThis as any).IS_REACT_ACT_ENVIRONMENT = true;

async function flushReact() {
  await act(async () => {
    await Promise.resolve();
    await new Promise((resolve) => window.setTimeout(resolve, 0));
  });
}

function renderAt(container: HTMLElement, path: string) {
  const root = createRoot(container);
  const queryClient = new QueryClient({ defaultOptions: { queries: { retry: false } } });
  return act(async () => {
    root.render(
      <MemoryRouter initialEntries={[path]}>
        <QueryClientProvider client={queryClient}>
          <Routes>
            <Route path="/deliverables/:deliverableId" element={<DeliverableDetail />} />
          </Routes>
        </QueryClientProvider>
      </MemoryRouter>,
    );
  });
}

const baseDetail = {
  id: "deliverable-1",
  companyId: "company-1",
  projectId: null,
  title: "Final report",
  summary: "Produced for the board.",
  audience: "human",
  createdAt: "2026-05-01T00:00:00.000Z",
  updatedAt: "2026-05-01T00:00:00.000Z",
  contentPath: "/api/attachments/abc/content",
  byteSize: 2048,
  originalFilename: "report.pdf",
  childIssue: { id: "child-1", identifier: "PAP-12", title: "Write report", status: "done" },
  rootIssue: { id: "root-1", identifier: "PAP-1", title: "Quarterly review", status: "in_progress" },
  agent: { id: "agent-1", name: "Astro", urlKey: "astro", icon: null },
  runId: "run-1",
  ancestors: [
    { id: "root-1", identifier: "PAP-1", title: "Quarterly review", status: "in_progress" },
  ],
  preview: null,
};

describe("DeliverableDetail page", () => {
  let container: HTMLDivElement;

  beforeEach(() => {
    container = document.createElement("div");
    document.body.appendChild(container);
  });

  afterEach(() => {
    container.remove();
    document.body.innerHTML = "";
    vi.clearAllMocks();
  });

  it("shows a generic preview, download, and links for non-image artifacts", async () => {
    getMock.mockResolvedValue({ ...baseDetail, contentType: "application/pdf" });

    await renderAt(container, "/deliverables/deliverable-1");
    await flushReact();
    await flushReact();

    expect(container.textContent).toContain("Final report");
    expect(container.textContent).toContain("Produced for the board.");
    // Side panel labels
    expect(container.textContent).toContain("Original request");
    expect(container.textContent).toContain("Worked on");
    expect(container.textContent).toContain("Generated by");
    expect(container.textContent).toContain("Astro");
    expect(container.textContent).toContain("PAP-1");
    expect(container.textContent).toContain("PAP-12");

    const downloadLinks = Array.from(container.querySelectorAll("a")).filter(
      (a) => a.getAttribute("href") === "/api/attachments/abc/content",
    );
    expect(downloadLinks.length).toBeGreaterThan(0);
    expect(downloadLinks[0]!.getAttribute("download")).toBe("report.pdf");

    // PDF should render an iframe preview
    const iframe = container.querySelector("iframe");
    expect(iframe?.getAttribute("src")).toBe("/api/attachments/abc/content");
  });

  it("renders an inline image when the artifact is an image", async () => {
    getMock.mockResolvedValue({ ...baseDetail, contentType: "image/png" });

    await renderAt(container, "/deliverables/deliverable-1");
    await flushReact();
    await flushReact();

    const img = container.querySelector("img");
    expect(img?.getAttribute("src")).toBe("/api/attachments/abc/content");
  });

  it("renders markdown previews inline for text deliverables", async () => {
    getMock.mockResolvedValue({
      ...baseDetail,
      audience: "internal",
      contentType: "text/markdown; charset=utf-8",
      originalFilename: "plan.md",
      preview: {
        kind: "markdown",
        body: "# Execution Plan\n\n- Step 1",
        truncated: false,
      },
    });

    await renderAt(container, "/deliverables/deliverable-1");
    await flushReact();
    await flushReact();

    expect(container.textContent).toContain("Execution Plan");
    expect(container.textContent).toContain("Internal");
  });

  it("hides the original-request row when the deliverable's child IS the root", async () => {
    getMock.mockResolvedValue({
      ...baseDetail,
      contentType: "text/markdown",
      rootIssue: null,
      ancestors: [],
    });

    await renderAt(container, "/deliverables/deliverable-1");
    await flushReact();
    await flushReact();

    expect(container.textContent).not.toContain("Original request");
    expect(container.textContent).toContain("Worked on");
  });
});
